diff a/Dockerfile.konflux b/Dockerfile.konflux	(rejected hunks)
@@ -1,4 +1,4 @@
-FROM registry.redhat.io/ubi8/python-312:1
+FROM registry.access.redhat.com/ubi9/python-312:1@sha256:7eff0198911e53c3c67634e82e6c156e3bd491149721e998280f104b7a185772
 
 ARG SOURCE_CODE=.
 
